/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tec.triviaid.proyectoaitrivia;

import tec.triviaid.proyectoaitrivia.TriviaController.TriviaController;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JProgressBar;

import tec.triviaid.proyectoaitrivia.TriviaController.Trivia;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        generatemenu = new javax.swing.JPanel();
        IntroLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        temaField = new javax.swing.JTextField();
        TemaLabel = new javax.swing.JLabel();
        numPreguntasField = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tiempoxPreguntaField = new javax.swing.JComboBox<>();
        TiempoxPreguntaLabel = new javax.swing.JLabel();
        iIdiomaField = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        correoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(new java.awt.CardLayout());

        generatemenu.setBackground(new java.awt.Color(232, 232, 232));
        generatemenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        generatemenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        IntroLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IntroLabel.setText("Bienvenido a Generador de Trivias!!!!!");
        IntroLabel.setToolTipText("");

        nombreField.setToolTipText("");
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        NombreLabel.setText("Nombre:");

        temaField.setToolTipText("");
        temaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaFieldActionPerformed(evt);
            }
        });

        TemaLabel.setText("Tema de conocimiento general:");

        numPreguntasField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12" }));
        numPreguntasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPreguntasFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad de Preguntas:");

        tiempoxPreguntaField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        tiempoxPreguntaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoxPreguntaFieldActionPerformed(evt);
            }
        });

        TiempoxPreguntaLabel.setText("Tiempo por Pregunta (minutos):");

        iIdiomaField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés", "Mandarín", "Francés" }));
        iIdiomaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iIdiomaFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Idioma:");

        generateButton.setText("Generar Trivia");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Correo electrónico:");

        javax.swing.GroupLayout generatemenuLayout = new javax.swing.GroupLayout(generatemenu);
        generatemenu.setLayout(generatemenuLayout);
        generatemenuLayout.setHorizontalGroup(
            generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generatemenuLayout.createSequentialGroup()
                .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(generatemenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numPreguntasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(iIdiomaField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temaField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TemaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiempoxPreguntaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TiempoxPreguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(generatemenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generatemenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IntroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        generatemenuLayout.setVerticalGroup(
            generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generatemenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IntroLabel)
                .addGap(34, 34, 34)
                .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLabel)
                    .addComponent(TemaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temaField))
                .addGap(27, 27, 27)
                .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPreguntasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TiempoxPreguntaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generatemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iIdiomaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoxPreguntaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        background.add(generatemenu, "card2");

        jLabel4.setText("MENU");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        background.add(menu, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void temaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temaFieldActionPerformed

    private void numPreguntasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPreguntasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPreguntasFieldActionPerformed

    private void iIdiomaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iIdiomaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iIdiomaFieldActionPerformed

    private void tiempoxPreguntaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoxPreguntaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoxPreguntaFieldActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
   
        //validate that all fields are filled
        if(nombreField.getText().isEmpty() || correoField.getText().isEmpty() || temaField.getText().isEmpty()){
            //show error message using a dialog box
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");

        }
        else{
            //set the data
            userdata.setNombre(nombreField.getText());
            userdata.setCorreo(correoField.getText());
            userdata.setCantidad_preguntas(Integer.parseInt(numPreguntasField.getSelectedItem().toString()));
            userdata.setIdioma(iIdiomaField.getSelectedItem().toString());
            userdata.setTema(temaField.getText());
            userdata.setTiempoxpregunta(Integer.parseInt(tiempoxPreguntaField.getSelectedItem().toString()));

            //generate the trivia
            
            //Trivia newTrivia = triviacontroller.generateTrivia(userdata.getIdioma(), userdata.getTema(), userdata.getCantidad_preguntas());
            Trivia newTrivia = new Trivia("prueba");

        
            
            //open pop window displaying that the trivia was generated, asking if the user wants to save it
            int result = javax.swing.JOptionPane.showConfirmDialog(this, "Trivia fue generada!!", "Quieres guardarla?", javax.swing.JOptionPane.YES_NO_OPTION);
            
            if(result == javax.swing.JOptionPane.YES_OPTION) {
                
                triviacontroller.SerializeTrivia(newTrivia, userdata.getNombre(), userdata.getTema(), userdata.getIdioma(), userdata.getCantidad_preguntas());
                generation_to_menu();
            } else {
                //return to the menu
                generation_to_menu();
                
            }





        }

      
        
    }//GEN-LAST:event_generateButtonActionPerformed


   


    public void generation_to_menu(){
        generatemenu.setVisible(false);
        menu.setVisible(true);
    }
    
    public UserData userdata;
    public TriviaController triviacontroller;

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            GUI gui = new GUI();
            //make it not resizable
            gui.setResizable(false);
            gui.setVisible(true);
            gui.userdata = new UserData();
            gui.triviacontroller = new TriviaController();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IntroLabel;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JLabel TemaLabel;
    private javax.swing.JLabel TiempoxPreguntaLabel;
    private javax.swing.JPanel background;
    public javax.swing.JTextField correoField;
    public javax.swing.JButton generateButton;
    public javax.swing.JPanel generatemenu;
    public javax.swing.JComboBox<String> iIdiomaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel menu;
    public javax.swing.JTextField nombreField;
    public javax.swing.JComboBox<String> numPreguntasField;
    public javax.swing.JTextField temaField;
    public javax.swing.JComboBox<String> tiempoxPreguntaField;
    // End of variables declaration//GEN-END:variables
}
